### ISSUE TITLE
Add GitHub Actions for squashing commits

### ISSUE THREAD

**Issue by aaa1115910** [aaa1115910/bv#196]
### Summary
This workflow will automatically squash all historical commits into a single commit for a specified branch.

---

### Workflow File Content

```yaml
name: Squash Commits

on:
  workflow_dispatch: # Allow manual trigger

jobs:
  squash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure Git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Reset to the first commit
        run: |
          git checkout --orphan temp-branch $(git rev-list --max-parents=0 HEAD)

      - name: Add all files
        run: |
          git add .

      - name: Create a new commit
        run: |
          git commit -m "Squashed all commits into one"

      - name: Force push the new commit
        run: |
          git branch -D main
          git checkout -b main
          git push --force
```

---

### Notes
- This workflow requires a manual trigger via the "workflow_dispatch" event.
- Once triggered, it will squash all commits on the `main` branch into a single commit.
- Ensure you want to overwrite the branch history before using this, as it will rewrite Git history.
